server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    # Do NOT register this server with itself
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    # Optional - disable self-preservation (for dev/test)
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
  instance:
    hostname: discovery-server
